### ISSUE TITLE
Lymphocyte assignments & results

### ISSUE THREAD

**Issue by rainersachs** [rainersachs/URAP.CA#2]
mainly for Peter and Ray

**Comment by rainersachs** [comment]
For next weeks Peter should:
1. Finish entering the data we already have.
2. Use the script Ray emailed to put the new TE-only one-ion models into the master lymphocyte .Rmd. Don't clutter up GitHub with the Sachs script. But save it on your own sandbox for further use later.
3. Prepare to ask questions.
4. write up the minutes of each Friday's  meeting.

In the long run the master lymphocyte .Rmd will need to contain 4 different HZE models: NTE-TE or TE-only; old or new. There also has to be a low LET model for protons and Helium 4 model.

In the very long run there have to be many more one-ion and mixed beam results in the data frame.

**Comment by rainersachs** [comment]
Here is what peter wrote for today's meeting minutes
"    1. I gave an overview of what I did last week:
       1.1 I simplified the code for getting the weighted RSS
        1.2 calculated the AIC and BIC for the models we have right now
        1.3 New TE was the worst in terms of AIC. I used Y_0 = 0
        1.4 LQ performed better than Q
    So the models that we have right now is the following:
        2.Old models:
            TE (I forgot to include this in the AIC BIC comparison)
            NTE: our IDER model for fibroblast
       3. New Models:
            TE: the one with only beta (1 parameter)
            NTE-TE: the Q model. 
    4. AIC/BIC is not a universal criteria for model selection. Apparently some radiologists really emphasize on parsimony (prefer fewer parameters).
   
Main task for next week:
    1. Add the old TE to the AIC/BIC comparisons. 
    2. Check whether the "factor" class objects are messing up the AIC/BIC and residual calculations 
    3. Stick to TE models to get the synergy part and keep writing the file

In the end we will prefer Q over LQ. But right now the LQ performs better than Q which is not expected. 
    For later: Use nlsLM, and make sure the "factor" thing in R is not affecting the results. 
    Take Y_0 = 0 for new and old TE, and for NTE-TE models, Y_0 = something else which you will get in 2 weeks after meeting with Hada to get the 24-color value?"

Ray is adding the following. Here are some clarifications. They apply to next week and later; the minutes of this week'd meeting are essentially correct, though I'm very surprised by some of the AIC results.
Clarification 0.  We plan to model only data on aberrations that are "apparently simple" (AS) in the painting protocol used (e.g. protocol 1,2,4), never visibly complex aberrations, in the foreseeable future.

Clarification 1. For next week Peter's 3 is the main task. Tasks 1 and 2 can be postponed.

Clarification 1.5. We don't yet know whether we will prefer Q over LQ in the end. For the near future we will simply assume Q until we have the whole calculation for a mixture of two Q one-ion DERs.

Clarification 2. If Y_0=0 for the raw data then Y_0=0 in the 24-color extrapolations.

Clarification 3. The meeting with Hada is mainly to decide how much of the overall lymphocyte data to include in a first paper.  Maybe best to confine attention to the data Peter has already entered and try to move fast. Maybe best to try to include all relevant Hada lymphocyte data and then presumably move much slower but more accurately. 

Clarification 4. As regards Y_0 (the background prevalence) I think we should not lump together all controls from different donors. I think probably all the male lymphocyte data Hada published came from 
one donor; if so all the male cells probably should be grouped together. Same comment for the female lymphocytes. If each of male and female came from one donor each, we could then run standard tests to see if they could be lumped together. I will have to ask Hada how many donors were involved and her ideas about what to lump together. For example if she changed techniques at some date does she think the newer and older data should be lumped.

Thanks Peter for a good meeting today and good minutes which clarified both our thinking!

**Comment by peterwangshichun** [comment]
[Recap of 3/2 meeting]:

1. I gave an overview of what I did last week:
1.1 I looked at the fit of the new TE model, added the AIC and BIC's to github. 
1.2 I made the TE version of the "MIXDER" function and produced the graph for the 3 ions we have information on, for lymphocytes. 
1.3 I realized that the derivative is equal to 0 at d = 0 (this is resolved by the new new TE with 2 parameters.

2. I should only look at TE for now and forget about the other models for a moment. 
3. The TE model has been changed to `Y_0 + (alpha + beta*F)(1-exp(-H)` where H = F * 30. 
4. We briefly went over how Monte Carlo works. I will see Andy next week to discuss about it further, ideally after he figures out how to speed up the run time of the code.
5. No meeting for the next 2 weeks. Will stay in touch on Github & Email. I can comment on a specific line of code if I am stuck somewhere.

Main task for next week:

1. Change the TE model (including the function, parameters, WRSS, AIC/BIC, and the ODE function). 
2. Carry on with the code (start the Monte Carlo part).
3. Meet with Andy.

Hope you have a great and productive meeting with Hada!

**Comment by peterwangshichun** [comment]
I commited to github last night the lymphocyte 95% CI (Monte Carlo) for 2-ion TE model. I updated the model to include alpha and beta.

**Comment by peterwangshichun** [comment]
[Recap of 4/1 meeting]:

Main points of the meeting:
1. We are dropping lymphocytes because of how much complex effects are present (this will invalidate the 4-color to 24-color conversion, thus nullify the data). Fibroblasts do not suffer from this dilemma because it has much fewer complex effects. 
 
2. I should be focusing on quality control work for Andy's fibroblast data file. This means cleaning up the code and looking for errors. 

3. The file should be in R. We agreed on a solution where I will create a folder on Github and run one Monte Carlo. The R plots will all be in a R file using this specific Monte Carlo result, and this R file will also be in that folder.

I am meeting Andy today and I will create that folder and the R file soon.

**Comment by rainersachs** [comment]
This issue is obsolete because we have given up on modeling the Hada lymphocyte data in the foreseeable future. All comments henceforth belong in the fibroblast issue.
